name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ljohr/portfolio:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f portolio-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name portfolio-container ljohr/portfolio:latest
